#!/usr/bin/env bash
# EvoRule Pre-commit Hook Installer
# Installs paradigm-gate.sh as the Git pre-commit hook.
# Source: GATES.md (pre-commit hook section)
# Usage: ./tools/install-hooks.sh
# Exit codes: 0 = success, 1 = hook already exists and user declined, 2 = error

set -euo pipefail

# Resolve repo root: walk up from script looking for .git/
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$SCRIPT_DIR"
while [ "$REPO_ROOT" != "/" ]; do
    if [ -d "$REPO_ROOT/.git" ] || [ -f "$REPO_ROOT/Cargo.toml" ]; then
        break
    fi
    REPO_ROOT="$(dirname "$REPO_ROOT")"
done
if [ "$REPO_ROOT" = "/" ]; then
    echo "ERROR: Could not find repo root (no .git/ or Cargo.toml found)" >&2
    exit 2
fi
cd "$REPO_ROOT"

# ---------- Config ----------
HOOKS_DIR=".git/hooks"
HOOK_FILE="$HOOKS_DIR/pre-commit"
GATE_SCRIPT="tools/paradigm-gate.sh"

# Check if the gate script exists
if [ ! -f "$GATE_SCRIPT" ]; then
    echo "ERROR: Gate script not found: $GATE_SCRIPT" >&2
    echo "Make sure $GATE_SCRIPT exists and is executable." >&2
    exit 2
fi

# Ensure hooks directory exists
mkdir -p "$HOOKS_DIR"

# ---------- Backup existing hook if present ----------
if [ -f "$HOOK_FILE" ]; then
    # Check if it's already our hook (by comparing content or shebang)
    if grep -q "paradigm-gate.sh" "$HOOK_FILE" 2>/dev/null; then
        echo "✅ pre-commit hook already installed (points to paradigm-gate.sh)."
        echo "   No changes made."
        exit 0
    else
        echo "⚠️  Existing pre-commit hook found: $HOOK_FILE"
        echo "   Backing it up to $HOOK_FILE.backup.$(date +%Y%m%d%H%M%S)"
        BACKUP_FILE="$HOOK_FILE.backup.$(date +%Y%m%d%H%M%S)"
        mv "$HOOK_FILE" "$BACKUP_FILE"
        echo "   Backup saved: $BACKUP_FILE"
    fi
fi

# ---------- Write new hook ----------
cat > "$HOOK_FILE" << 'EOF'
#!/usr/bin/env bash
# EvoRule pre-commit hook: run paradigm-gate.sh
# This hook is auto-generated by tools/install-hooks.sh.
# To bypass this hook (not recommended), use `git commit --no-verify`.

set -euo pipefail

# Resolve repo root (same logic as paradigm-gate.sh)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$SCRIPT_DIR"
while [ "$REPO_ROOT" != "/" ]; do
    if [ -d "$REPO_ROOT/.git" ] || [ -f "$REPO_ROOT/Cargo.toml" ]; then
        break
    fi
    REPO_ROOT="$(dirname "$REPO_ROOT")"
done
if [ "$REPO_ROOT" = "/" ]; then
    echo "ERROR: Could not find repo root" >&2
    exit 1
fi
cd "$REPO_ROOT"

# Run the paradigm gate
exec ./tools/paradigm-gate.sh
EOF

# Make it executable
chmod +x "$HOOK_FILE"

echo "✅ pre-commit hook installed successfully."
echo "   Hook will run: ./tools/paradigm-gate.sh"
echo "   To bypass (not recommended): git commit --no-verify"
exit 0